### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by f-fathurrahman** [JuliaMolSim/Libxc.jl#2]
Hi @unkcpz , thank you very much for your contribution to PWDFT.jl.

Do you have any plan for providing binary of Libxc for Windows?

**Comment by unkcpz** [comment]
I have tried to compile Libxc uning BinaryBuilder for windows, however, always get stuck somewhere. I'll make more test.
Fortunately, LibSymlib built successfully in windows.
Do you have plan to make PWDFT.jl compatible in Windows?
